trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: macos-latest

name: $(mauiPackVersion).(Rev:r)

variables:
  - group: 'Shared'
  - name: 'buildConfiguration'
    value: 'release'
  - name: 'PathToMsBuildOnMacOS'
    value: 'mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll'
  - name: 'projectPath'
    value: 'FourTwenty.Mobile.Maui/FourTwenty.Mobile.Maui.csproj'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install latest Nuget'
    inputs:
      versionSpec: 6.x

  - script: dotnet restore $(projectPath)
    displayName: 'Restore NuGet packages'

  - script: echo "##vso[task.setvariable variable=ReleaseNotes]$(cat 'releasenotes.maui.txt')"
    displayName: 'Create release notes from file'

  - script: dotnet pack $(projectPath) -o '$(Build.ArtifactStagingDirectory)/nuget' --configuration $(buildConfiguration) --no-restore -p:PackageVersion=$(Build.BuildNumber) -p:Version=$(Build.BuildNumber) -p:PackageReleaseNotes='$(ReleaseNotes)'
    displayName: 'Pack nuget'

  - publish: $(Build.ArtifactStagingDirectory)/nuget
    artifact: nuget
    displayName: 'Publish nuget artifact'
